# Generated by Django 4.2.4 on 2023-09-02 08:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0004_rename_items_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item',
            new_name='items',
        ),
    ]
